server:
  port: 8888
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: https://github.com/julianoborba/ddos-mitigation-with-bucket4j
          search-paths: /config