spring:
  application:
    name: eureka

server:
  port: 8302

logging:
  file: target/eureka-service.log

management:
  security:
    roles: ADMIN
  context-path: /management
  health:
    mail:
      enable: false

security:
  user:
    name: eureka
    password: eureka
    role: USER,ADMIN

eureka:
  datacenter: seattle
  enviroment: desenv
  instance:
    appname: eureka-service
    securePort: ${server.port}
    instanceId: ${eureka.instance.appname}:${spring.application.instance_id:${random.value}}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    status-page-url-path: ${management.context-path}/info
    health-check-url-path: ${management.contex-path}/health
    metadata-map:
      profile: ${spring.profile.active}
      version: ${info.project.version}
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      eviction-interval-timer-in-ms: 1000
    instance:
      preferIpAddress: true	
      enable-self-preservation: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    dashboard:
      path: /registry

